# plots.py - Plotting functions used by the app
import plotly.express as px
import pandas as pd
import streamlit as st
from colors import Colors

# ============================================================================
# TAB 2: SERVICE DATA PLOTS
# ============================================================================

def plot_peak_hours(df):
    if df is None or df.empty:
        st.info("No data for peak hours")
        return
    fig = px.bar(df, x="hour", y="visit_count", text_auto=True, title="Peak Customer Arrival Hours")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, xaxis_title="Hour of Day", yaxis_title="Number of Visits", title_x=0.5)
    st.plotly_chart(fig, use_container_width=True)

def plot_weekday_visit_counts(df):
    if df is None or df.empty:
        st.info("No weekday visit data")
        return
    df = df.copy()
    df["is_weekend"] = df["weekday"].isin(["Saturday","Sunday"])
    fig = px.bar(df, x="weekday", y="visit_count", color="is_weekend", text_auto=True, title="Customer Visits by Weekday", color_discrete_map={True: Colors.ROYAL_GOLD, False: Colors.DEEP_SAPPHIRE})
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, xaxis_title="Weekday", yaxis_title="Number of Visits", showlegend=False, title_x=0.5, bargap=0.2)
    st.plotly_chart(fig, use_container_width=True)

def plot_service_counts(df):
    if df is None or df.empty:
        st.info("No service count data")
        return
    fig = px.bar(df, x="Service", y="count", text_auto=True, title="Service Usage Count")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, title_x=0.5, showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

def plot_spend_vs_visits(df):
    if df is None or df.empty:
        st.info("No spend vs visits data")
        return
    fig = px.scatter(df, x="visits", y="total_spent", size="avg_spend_per_visit", hover_name="Name", title="Customer Spend vs Visit Ratio")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, xaxis_title="Number of Visits", yaxis_title="Total Spent (₹)", title_x=0.5)
    st.plotly_chart(fig, use_container_width=True)

def plot_employee_performance(df1, df2):
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("### Services Rendered by Employee")
        if df1 is None or df1.empty:
            st.info("No employee service data")
        else:
            fig1 = px.bar(df1, x="employee", y="service_count", text_auto=True, title="")
            fig1.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, yaxis_title="Services", title_x=0.5, showlegend=False)
            st.plotly_chart(fig1, use_container_width=True)
    with col2:
        st.markdown("### Revenue Generated by Employee")
        if df2 is None or df2.empty:
            st.info("No employee revenue data")
        else:
            fig2 = px.bar(df2, x="employee", y="total_revenue", text_auto=True)
            fig2.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, yaxis_title="Revenue (₹)", title_x=0.5, showlegend=False)
            st.plotly_chart(fig2, use_container_width=True)

# ============================================================================
# TAB 3: PRODUCT DATA PLOTS
# ============================================================================

def plot_sales_by_day(df):
    if df is None or df.empty:
        st.info("No sales-by-day data")
        return
    weekday_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    df = df.copy()
    if 'day_of_week' not in df.columns:
        st.info("No day_of_week column")
        return
    df["day_of_week"] = pd.Categorical(df["day_of_week"], categories=weekday_order, ordered=True)
    df = df.sort_values("day_of_week")
    fig = px.line(df, x="day_of_week", y="total_sold", markers=True, text="total_sold", title="Sales Trend by Day of Week")
    fig.update_traces(textposition="top center")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, xaxis_title="Day of Week", yaxis_title="Total Sales (₹)", title_x=0.5)
    st.plotly_chart(fig, use_container_width=True)

def plot_top_products(df):
    if df is None or df.empty:
        st.info("No product data")
        return
    fig = px.bar(df.head(10), x="product", y="sold_count", text_auto=True, title="Top 10 Best-Selling Products")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, title_x=0.5, showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

def plot_employee_revenue(df):
    if df is None or df.empty:
        st.info("No employee revenue data")
        return
    fig = px.bar(df, x="employee", y="total_revenue", text_auto=True)
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, yaxis_title="Total Revenue (₹)", title_x=0.5, showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

def plot_employee_sales(df):
    if df is None or df.empty:
        st.info("No employee product sales data")
        return
    fig = px.bar(df, x="employee", y="total_products_sold", text_auto=True, title="Employee Product Sales Count")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, yaxis_title="Total Products Sold", title_x=0.5, showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

def plot_incentive_by_employee(df):
    st.markdown("### Employee Incentives Leaderboard (Current Year)")
    if df is None or df.empty:
        st.info("No incentive data")
        return
    fig = px.bar(df, x="employee", y="incentive_amount", text_auto=True, title="Employee Incentive Earnings")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, yaxis_title="Incentive Amount (₹)", title_x=0.5, showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

# ============================================================================
# TAB 4 / TAB 5: CALENDAR & STAFF PLOTS
# ============================================================================

def plot_monthly_calendar_heatmap(df):
    if df is None or df.empty:
        st.info("No booking data for calendar view")
        return
    df = df.copy()
    if 'date' not in df.columns:
        st.info("No date column in heatmap data")
        return
    df["day"] = pd.to_datetime(df["date"]).dt.day
    df["weekday"] = pd.to_datetime(df["date"]).dt.day_name()
    fig = px.density_heatmap(df, x="day", y="weekday", z="booking_count", title="Monthly Booking Heatmap")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, height=400, title_x=0.5)
    st.plotly_chart(fig, use_container_width=True)

def plot_employee_timeline(df, target_date):
    """Render employee schedule timeline (Gantt chart)"""
    if df.empty:
        st.info("No bookings scheduled for today")
        return

    # Create timeline data
    timeline_data = []
    for _, row in df.iterrows():
        hour, minute = map(int, row["Time Slot"].split(":"))

        # Fix: construct full timestamp
        date_obj = pd.to_datetime(target_date).date()
        start_time = pd.Timestamp(
            year=date_obj.year,
            month=date_obj.month,
            day=date_obj.day,
            hour=hour,
            minute=minute
        )

        end_time = start_time + pd.Timedelta(minutes=row["Duration"])

        timeline_data.append({
            "Employee": row["Preferred Employee"],
            "Start": start_time,
            "End": end_time,
            "Service": row["Service Booked"],
            "Customer": row["Name"]
        })

    timeline_df = pd.DataFrame(timeline_data)

    fig = px.timeline(
        timeline_df,
        x_start="Start",
        x_end="End",
        y="Employee",
        color="Service",
        hover_data=["Customer"],
        title="Employee Schedule Timeline",
        color_discrete_sequence=Colors.CHART_PALETTE
    )

    fig.update_layout(
        paper_bgcolor=Colors.BG_DARK,
        plot_bgcolor=Colors.BG_CARD,
        font={"color": Colors.TEXT_PRIMARY},
        xaxis_title="Time",
        yaxis_title="Employee",
        height=400,
        title_x=0.5
    )

    st.plotly_chart(fig, use_container_width=True)

def plot_leave_calendar_heatmap(df):
    if df is None or df.empty:
        st.info("No leave data for calendar view")
        return
    df = df.copy()
    if 'date' not in df.columns:
        st.info("No date column")
        return
    df["day"] = pd.to_datetime(df["date"]).dt.day
    df["weekday"] = pd.to_datetime(df["date"]).dt.day_name()
    fig = px.density_heatmap(df, x="day", y="weekday", z="leave_count", title="Leave Calendar Heatmap")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, height=400, title_x=0.5)
    st.plotly_chart(fig, use_container_width=True)

def plot_attendance_by_staff(df):
    if df is None or df.empty:
        st.info("No attendance data")
        return
    fig = px.bar(df, x="Staff Name", y="attendance_pct", text="attendance_pct", title="Attendance by Staff (Last 30 Days)")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, height=400, title_x=0.5, showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

def plot_staff_performance_trend(df):
    if df is None or df.empty:
        st.info("No attendance trend data")
        return
    fig = px.line(df, x="Date", y="attendance_pct", color="Staff Name", markers=True, title="Staff Performance Trend")
    fig.update_layout(paper_bgcolor=Colors.BG_DARK, plot_bgcolor=Colors.BG_CARD, font={"color": Colors.TEXT_PRIMARY}, height=400, title_x=0.5)
    st.plotly_chart(fig, use_container_width=True)


# ============================
#  BOOKING SOURCE DISTRIBUTION
# ============================

import plotly.express as px

def plot_booking_source_distribution(df):
    """
    Shows distribution of where the booking came from
    (e.g., Call, WhatsApp, Walk-in, Instagram, Website, Referral, etc.)
    """

    # Detect the booking source column automatically
    source_cols = [col.lower() for col in df.columns]

    if "source" in source_cols:
        source_col = df.columns[source_cols.index("source")]
    elif "booking source" in source_cols:
        source_col = df.columns[source_cols.index("booking source")]
    else:
        raise ValueError("Booking source column not found in dataframe")

    # Count distribution
    dist = df[source_col].value_counts().reset_index()
    dist.columns = ["source", "count"]

    fig = px.bar(
        dist,
        x="source",
        y="count",
        title="Distribution of Booking Source",
        text="count",
    )

    fig.update_traces(textposition="outside")
    fig.update_layout(
        xaxis_title="Source",
        yaxis_title="Number of Bookings",
        bargap=0.3,
    )

    return fig
